### ISSUE TITLE
Use the Promise implementation set in the configuration all across good-guy

### ISSUE THREAD

**Issue by domeq** [Schibsted-Tech-Polska/good-guy-http#10]
Even though I use native Promises, there are a few places e.g. cache adapters that have a hardcoded bluebird usage:
https://github.com/Schibsted-Tech-Polska/good-guy-http/search?utf8=%E2%9C%93&q=require%28%27bluebird%27%29

This ends up with 2 different Promise implementations and results in the following error when working in `NODE_ENV=development` 
http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it 

Ideally, the promise implementation chosen in the main configuration should be injected into all other places to make it consistent.

**Comment by kjarmicki** [comment]
> Ideally, the promise implementation chosen in the main configuration should be injected into all other places to make it consistent

True for good-guy core logic and provided caches, not necessarily for tests.

This might also be a good time to drop Bluebird completely in favor of native Promises.

**Comment by domeq** [comment]
I see no reason not to - I'm not using Bluebird anywhere anymore :)

**Comment by kjarmicki** [comment]
Oh look, it's Easter, time to clean up... old issues :sweat_smile: 
Implemented and released with `1.10.3`, closing.
