### ISSUE TITLE
Add possibility to cancel requests

### ISSUE THREAD

**Issue by pdziok** [Schibsted-Tech-Polska/good-guy-http#12]
My current use case scenario depends on services that are supposed to reply fast and therefore are queried with rather low timeout set. As in real world sometimes there happen some connectivity issues so my application suffers from them once in a while.

My app is using one of the databases with HTTP API. I would like to be able to abort currently triggered request or cancel further request processing (e.g. retrying) when external request to my app is cancelled so I don't additionally overload my DB with requests that results won't be used.

Library `request` used underneath have method in the API to abort request: https://github.com/request/request/blob/master/request.js#L1133. It's used in `request-promise` on cancelled promise: https://github.com/request/request-promise/blob/master/lib/rp.js#L38.

_PS. I'm not heavily attached to any of the methods in given examples._

**Comment by kjarmicki** [comment]
@pdziok feature was implemented, key decisions:
- `.abort()` method is now exposed on promised requests returned from Good Guy instances
- aborting request rejects promise with error code `EREQUESTABORED`
- aborted requests are not retried

If this is ok I'll add appropriate entry in docs and release it

**Comment by kjarmicki** [comment]
@pdziok for time being I've put this feature behind a flag (`GG_ABORTABLE_REQUEST`) because I'll be doing another release soon

**Comment by kjarmicki** [comment]
hey @pdziok have you checked out if applied change works for you?

**Comment by kjarmicki** [comment]
Feature flag has been removed and this feature is now live
