### ISSUE TITLE
idempotent override broken

### ISSUE THREAD

**Issue by trotha01** [Schibsted-Tech-Polska/good-guy-http#18]
If I make a request `makeRequest({ url: url, idempotent: true})` then the `makeRequest()` function is called with `req.idempotent = true`

Then `idempotent = true` is set in `additionalRequestConfig` and removed from `req` and `reconfigure()` is called, which recurses and calls `makeRequest()` again.

When we get to `isIdempotent()` in the recurse, it is no longer set on `req`

Please let me know if I am missing something.

**Comment by bukowskiadam** [comment]
We no longer use this library, so we've decided to deprecate it and archive the repository.
