### ISSUE TITLE
Response size checked after unzipping

### ISSUE THREAD

**Issue by winiarro** [Schibsted-Tech-Polska/good-guy-http#20]
It looks like response size is checked after the request is unzipped, so it's invariant to actual response size that is received with gzip flag. As a result I needed to change maxResponseSize parameter although response was just over 100kb, but after unzipping was over 1MB. Is it deliberate behaviour? 

Library version: 1.12.2

**Comment by bukowskiadam** [comment]
I am sorry that nobody answered your question. We're no longer using this library and we've decided to deprecate it and archive the repository.
